### ISSUE TITLE
Create user account within factory

### ISSUE THREAD

**Issue by noahsw** [versolearning/meteor-factory#20]
I'm having trouble creating a user account on the fly. Something like this:

```
Factory.define('team', Teams, {
  name: () => faker.lorem.words(),
  userId: () => {
    const email = faker.internet.email();
    const password = faker.lorem.words(1);
    Accounts.createUser({ email, password });

    if (Meteor.userId()) return Meteor.userId();
    return Accounts.findUserByEmail(email)._id;
  },
});
```

Since this factory can be both run on client and server, there are differences in how `Meteor.userId()` works.

On client tests, I get this error: `Accounts.findUserByEmail is not a function`
On server tests, I get: `Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.` (but using `this.userId` results in a different error)

Any tips? Great package btw!

**Comment by dburles** [comment]
Thanks @noahsw I would recommend creating a user factory and passing it into the team factory. Something like:

```js
Factory.define('user', Meteor.users, {
  username: () => faker.lorem.words(),
  profile: {
    firstName: () => faker.name.firstName(),
    lastName: () => faker.name.lastName(),
  },
  emails() {
    return [{
      address: faker.internet.email(),
      verified: false,
    }];
  },
});

Factory.define('team', Teams, {
  name: () => faker.lorem.words(),
  userId: Factory.get('user'),
});
```

**Comment by noahsw** [comment]
Beautiful! Thx!

**Comment by noahsw** [comment]
Hmm, actually... my tests run fine the first few times and then they randomly start firing this:
```
Error: insertDocument :: caused by :: 11000 E11000 duplicate key error index: meteor.users.$username_1  dup key: { : "sit" }
    at Object.Future.wait (/Users/noah/.meteor/packages/meteor-tool/.1.3.5_1.mj1j7l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)
    at MongoConnection.<anonymous> (packages/meteor/helpers.js:119:1)
    at MongoConnection.(anonymous function) (packages/mongo/mongo_driver.js:736:49)
    at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/insert.js:48:1)
    at Object.collection.(anonymous function) [as insert] (packages/matb33_collection-hooks/collection-hooks.js:117:1)
    at [object Object].insert (packages/mongo/collection.js:528:37)
    at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core/lib/collection2.js:191:1)
    at Function.Factory._create (packages/dburles:factory/factory.js:113:31)
    at Function.Factory.create (packages/dburles:factory/factory.js:120:26)
    at makeRelation (packages/dburles:factory/factory.js:45:22)
    - - - - -
    at Object.toError (/Users/noah/.meteor/packages/npm-mongo/.1.4.45.1n9eimd++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /Users/noah/.meteor/packages/npm-mongo/.1.4.45.1n9eimd++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/collection/core.js:116:29
    at /Users/noah/.meteor/packages/npm-mongo/.1.4.45.1n9eimd++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1197:7
    at /Users/noah/.meteor/packages/npm-mongo/.1.4.45.1n9eimd++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1905:9
    at Server.Base._callHandler (/Users/noah/.meteor/packages/npm-mongo/.1.4.45.1n9eimd++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /Users/noah/.meteor/packages/npm-mongo/.1.4.45.1n9eimd++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
    at [object Object].MongoReply.parseBody (/Users/noah/.meteor/packages/npm-mongo/.1.4.45.1n9eimd++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/Users/noah/.meteor/packages/npm-mongo/.1.4.45.1n9eimd++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
    at [object Object].<anonymous> (/Users/noah/.meteor/packages/npm-mongo/.1.4.45.1n9eimd++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
```

I've literally copied your code verbatim. See https://github.com/league-wins-pool/league-wins-pool/commit/2de1f4829ba52628ed1dad31a5d3a59692a854bd

**Comment by dburles** [comment]
Make the username more random :)

**Comment by noahsw** [comment]
Ha - I added some random characters afterwards and that seems to help. I had assumed faker had its own randomness.

**Comment by diavrank** [comment]
I share an example working using **Meteor 2.3**:

_Definition_
```javascript

Factory.define('player', Meteor.users, {
	username: () => faker.internet.userName(),
	profile: {
		name: () => faker.name.findName(),
		profile: () => StaticProfiles.player.name,
		birthday: () => faker.date.between('1990-01-01', '2000-11-05'),
		favoriteSport: () => faker.helpers.randomize(['football', 'basketball', 'voleyball']),
		defaultSearchRadius: () => faker.datatype.number(BusinessRules.maxSearchRadius),
		sex: () => faker.helpers.randomize(['M', 'F', 'NS'])
	},
	services: {
		password: {
			bcrypt: () => faker.internet.password()
		},
		resume: {
			loginTokens: () => []
		}
	},
	emails: () => [{ address: faker.internet.email(), verified: true }],
	createdAt: () => new Date(),
	status: {
		online: () => false
	}
});
```

_Usage:_

```javascript
// @ts-ignore
import { Factory } from 'meteor/dburles:factory';
import { updateFavoriteSportMethod } from '/imports/api/Player/Methods/UpdateFavoriteSportMethod';
// @ts-ignore
import { resetDatabase } from 'meteor/xolvio:cleaner';
import chai from 'chai';
import { Meteor } from 'meteor/meteor';
import faker from 'faker';

faker.locale = 'es_MX';

describe('player.updateFavoriteSport', function() {
	let userId: string;
	let existingPhoneNumber = faker.phone.phoneNumber('+52##########');

	before(function() {
		resetDatabase();
		const player = Factory.create('player', { 'profile.phone': existingPhoneNumber });
		userId = player._id;
	});
	it('Correct favorite sport', function() {
		const responseMessage = updateFavoriteSportMethod._execute({ userId },
			{ favoriteSport: faker.helpers.randomize(['football', 'basketball', 'volleyball']) });
		chai.assert.equal(responseMessage.message, 'Se actualizó el deporte favorito');
	});
	it('Incorrect favorite sport', function() {
		chai.assert.throws(() => {
			updateFavoriteSportMethod._execute({ userId }, { favoriteSport: 'tennis' });
		}, Meteor.Error, 'La información introducida no es válida');
	});
});
```

**Notes:**

Using **socialize:user-presence** package which uses simple-schema, so, it is needed to have that structure.
